SP203
Jifflis/myBudget-flutter-app pull request #19
Opened 2021-05-04 04:02 UTC by Pedot12

Trigger  Home page Plus icons

2021-05-06 02:07 UTC, japheth26 requested changes
Just change the route from add transaction to add budget.

2021-05-06 02:07 UTC, japheth26 commented on lib/view/screen/home_screen.dart
> +                  Routes.pushNamed(Routes.SCREEN_ADD_TRANSACTION,
Don't remove route for add budget in home screen. Instead, transfer route for add transaction in transaction screen add button.

2021-05-12 02:01 UTC, jifflisLIG approved these changes

2021-05-12 02:02 UTC, japheth26 approved these changes

2021-05-12 02:02 UTC, merged